services:

  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"

  policy-service:
    build: ./policy-service
    ports:
      - "5001:5001"

  resource-service:
    build: ./ressource-service
    ports:
      - "5002:5002"
    depends_on:
      - policy-service